CREATE TABLE "pg-drizzle_conversation" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "pg-drizzle_conversation_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"contactId" integer NOT NULL,
	"ownerId" varchar(255) NOT NULL,
	"sellingContext" text NOT NULL,
	"createdAt" timestamp with time zone NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "pg-drizzle_message" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "pg-drizzle_message_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"conversationId" integer NOT NULL,
	"role" varchar(20) NOT NULL,
	"content" text NOT NULL,
	"createdAt" timestamp with time zone NOT NULL
);
--> statement-breakpoint
ALTER TABLE "pg-drizzle_conversation" ADD CONSTRAINT "pg-drizzle_conversation_contactId_pg-drizzle_contact_id_fk" FOREIGN KEY ("contactId") REFERENCES "public"."pg-drizzle_contact"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pg-drizzle_conversation" ADD CONSTRAINT "pg-drizzle_conversation_ownerId_user_id_fk" FOREIGN KEY ("ownerId") REFERENCES "public"."user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pg-drizzle_message" ADD CONSTRAINT "pg-drizzle_message_conversationId_pg-drizzle_conversation_id_fk" FOREIGN KEY ("conversationId") REFERENCES "public"."pg-drizzle_conversation"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "conversation_owner_idx" ON "pg-drizzle_conversation" USING btree ("ownerId");--> statement-breakpoint
CREATE INDEX "message_conversation_idx" ON "pg-drizzle_message" USING btree ("conversationId");