CREATE TABLE "pg-drizzle_membership" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "pg-drizzle_membership_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"userId" varchar(255) NOT NULL,
	"organizationId" integer NOT NULL,
	"role" varchar(20) NOT NULL,
	"createdAt" timestamp with time zone NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "pg-drizzle_organization" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "pg-drizzle_organization_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(200) NOT NULL,
	"createdAt" timestamp with time zone NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
DROP TABLE "pg-drizzle_ai_preferences" CASCADE;--> statement-breakpoint
DROP TABLE "pg-drizzle_credit_balance" CASCADE;--> statement-breakpoint
ALTER TABLE "pg-drizzle_membership" ADD CONSTRAINT "pg-drizzle_membership_userId_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pg-drizzle_membership" ADD CONSTRAINT "pg-drizzle_membership_organizationId_pg-drizzle_organization_id_fk" FOREIGN KEY ("organizationId") REFERENCES "public"."pg-drizzle_organization"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "membership_user_org_idx" ON "pg-drizzle_membership" USING btree ("userId","organizationId");--> statement-breakpoint
CREATE INDEX "membership_org_idx" ON "pg-drizzle_membership" USING btree ("organizationId");--> statement-breakpoint
CREATE INDEX "organization_name_idx" ON "pg-drizzle_organization" USING btree ("name");