CREATE TABLE "pg-drizzle_budget" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "pg-drizzle_budget_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"organizationId" integer NOT NULL,
	"totalPersonDays" integer NOT NULL,
	"periodStart" timestamp with time zone NOT NULL,
	"periodEnd" timestamp with time zone NOT NULL,
	"createdAt" timestamp with time zone NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "pg-drizzle_initiative" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "pg-drizzle_initiative_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"organizationId" integer NOT NULL,
	"name" varchar(200) NOT NULL,
	"description" text,
	"status" varchar(20) NOT NULL,
	"isDefaultBucket" boolean DEFAULT false NOT NULL,
	"proposedById" varchar(255),
	"approvedById" varchar(255),
	"createdAt" timestamp with time zone NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "pg-drizzle_time_entry" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "pg-drizzle_time_entry_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"userId" varchar(255) NOT NULL,
	"initiativeId" integer NOT NULL,
	"person_days" real NOT NULL,
	"weekOf" timestamp with time zone NOT NULL,
	"note" text,
	"createdAt" timestamp with time zone NOT NULL
);
--> statement-breakpoint
ALTER TABLE "pg-drizzle_budget" ADD CONSTRAINT "pg-drizzle_budget_organizationId_pg-drizzle_organization_id_fk" FOREIGN KEY ("organizationId") REFERENCES "public"."pg-drizzle_organization"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pg-drizzle_initiative" ADD CONSTRAINT "pg-drizzle_initiative_organizationId_pg-drizzle_organization_id_fk" FOREIGN KEY ("organizationId") REFERENCES "public"."pg-drizzle_organization"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pg-drizzle_initiative" ADD CONSTRAINT "pg-drizzle_initiative_proposedById_user_id_fk" FOREIGN KEY ("proposedById") REFERENCES "public"."user"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pg-drizzle_initiative" ADD CONSTRAINT "pg-drizzle_initiative_approvedById_user_id_fk" FOREIGN KEY ("approvedById") REFERENCES "public"."user"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pg-drizzle_time_entry" ADD CONSTRAINT "pg-drizzle_time_entry_userId_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pg-drizzle_time_entry" ADD CONSTRAINT "pg-drizzle_time_entry_initiativeId_pg-drizzle_initiative_id_fk" FOREIGN KEY ("initiativeId") REFERENCES "public"."pg-drizzle_initiative"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "budget_org_idx" ON "pg-drizzle_budget" USING btree ("organizationId");--> statement-breakpoint
CREATE UNIQUE INDEX "budget_org_period_idx" ON "pg-drizzle_budget" USING btree ("organizationId","periodStart","periodEnd");--> statement-breakpoint
CREATE INDEX "initiative_org_idx" ON "pg-drizzle_initiative" USING btree ("organizationId");--> statement-breakpoint
CREATE INDEX "initiative_status_idx" ON "pg-drizzle_initiative" USING btree ("status");--> statement-breakpoint
CREATE INDEX "time_entry_user_idx" ON "pg-drizzle_time_entry" USING btree ("userId");--> statement-breakpoint
CREATE INDEX "time_entry_initiative_idx" ON "pg-drizzle_time_entry" USING btree ("initiativeId");--> statement-breakpoint
CREATE UNIQUE INDEX "time_entry_user_initiative_week_idx" ON "pg-drizzle_time_entry" USING btree ("userId","initiativeId","weekOf");