CREATE TABLE "pg-drizzle_coaching_message" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "pg-drizzle_coaching_message_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"sessionId" integer NOT NULL,
	"role" varchar(20) NOT NULL,
	"content" text NOT NULL,
	"createdAt" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "pg-drizzle_coaching_session" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "pg-drizzle_coaching_session_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"userId" varchar(255) NOT NULL,
	"organizationId" integer NOT NULL,
	"weekOf" timestamp with time zone NOT NULL,
	"status" varchar(20) NOT NULL,
	"createdAt" timestamp with time zone NOT NULL,
	"completedAt" timestamp with time zone
);
--> statement-breakpoint
ALTER TABLE "pg-drizzle_coaching_message" ADD CONSTRAINT "pg-drizzle_coaching_message_sessionId_pg-drizzle_coaching_session_id_fk" FOREIGN KEY ("sessionId") REFERENCES "public"."pg-drizzle_coaching_session"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pg-drizzle_coaching_session" ADD CONSTRAINT "pg-drizzle_coaching_session_userId_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pg-drizzle_coaching_session" ADD CONSTRAINT "pg-drizzle_coaching_session_organizationId_pg-drizzle_organization_id_fk" FOREIGN KEY ("organizationId") REFERENCES "public"."pg-drizzle_organization"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "coaching_message_session_idx" ON "pg-drizzle_coaching_message" USING btree ("sessionId");--> statement-breakpoint
CREATE INDEX "coaching_session_user_idx" ON "pg-drizzle_coaching_session" USING btree ("userId");--> statement-breakpoint
CREATE UNIQUE INDEX "coaching_session_user_week_idx" ON "pg-drizzle_coaching_session" USING btree ("userId","weekOf");--> statement-breakpoint
CREATE INDEX "coaching_session_org_idx" ON "pg-drizzle_coaching_session" USING btree ("organizationId");