CREATE TABLE "pg-drizzle_slack_user_mapping" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "pg-drizzle_slack_user_mapping_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"userId" varchar(255) NOT NULL,
	"slackUserId" varchar(50) NOT NULL,
	"slackTeamId" varchar(50) NOT NULL,
	"createdAt" timestamp with time zone NOT NULL
);
--> statement-breakpoint
ALTER TABLE "pg-drizzle_slack_user_mapping" ADD CONSTRAINT "pg-drizzle_slack_user_mapping_userId_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "slack_user_mapping_user_idx" ON "pg-drizzle_slack_user_mapping" USING btree ("userId");--> statement-breakpoint
CREATE UNIQUE INDEX "slack_user_mapping_slack_idx" ON "pg-drizzle_slack_user_mapping" USING btree ("slackUserId","slackTeamId");