CREATE TABLE "pg-drizzle_slack_invitation" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "pg-drizzle_slack_invitation_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"token" varchar(64) NOT NULL,
	"slackUserId" varchar(50) NOT NULL,
	"slackTeamId" varchar(50) NOT NULL,
	"organizationId" integer,
	"expiresAt" timestamp with time zone NOT NULL,
	"usedAt" timestamp with time zone,
	"createdAt" timestamp with time zone NOT NULL,
	CONSTRAINT "pg-drizzle_slack_invitation_token_unique" UNIQUE("token")
);
--> statement-breakpoint
ALTER TABLE "pg-drizzle_slack_invitation" ADD CONSTRAINT "pg-drizzle_slack_invitation_organizationId_pg-drizzle_organization_id_fk" FOREIGN KEY ("organizationId") REFERENCES "public"."pg-drizzle_organization"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "slack_invitation_slack_idx" ON "pg-drizzle_slack_invitation" USING btree ("slackUserId","slackTeamId");